baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "indabax-website-base"
timeZone = "Africa/Johannesburg"
title = "Deep Learning Indabaùïè South Africa"
[[menu.main]]
URL = "schedule"
identifier = "schedule"
name = "Schedule"
weight = 1
[[menu.main]]
URL = "faq"
identifier = "faq"
name = "FAQ"
weight = 1
[[menu.main]]
URL = "register"
identifier = "register"
name = "Register"
weight = 2
[[menu.main]]
URL = "speakers"
identifier = "speakers"
name = "Speakers"
weight = 3
[[menu.main]]
URL = "partners"
identifier = "partners"
name = "Partners"
weight = 4
[[menu.main]]
URL = "news"
identifier = "news"
name = "News"
weight = 2
[[menu.main]]
URL = "archive"
identifier = "archive"
name = "Archive"
weight = 8
[[menu.main]]
URL = "about"
identifier = "about"
name = "About"
weight = 9
[params]
address = "University of the Witwatersrand"
address_details = ""
author = "Christopher Currin"
copyright = "Copyright &copy;{{now}} Deep Learning IndabaX South Africa NPC"
decor = true
description = "Deep Learning Indabaùïè South Africa"
email = "info@indabax.co.za"
google_analytics_id = "G-JGG34NXR8G"
home = "Home"
home_bg = "https://source.unsplash.com/aMBhrrveocw/1920x1200"
logo = "images/dlxza_logo white.png"
phone = ""
short_title = "#indabaX"
theme_color = "#9BC782"
theme_color_secondary = "#C9AB81"
[params.contact]
enable = true
floating = true
form_action = "https://formspree.io/f/xayvlkkb"
homepage = true
[params.cookies]
enable = true
expire_days = 20
[params.faculty]
badges = false 
order = "asc" # asc, desc
show_track = true 
sortby = "name" # name, max_year, etc.
[[params.footermenu.about]]
link = "about/code-of-conduct"
name = "Code of Conduct"
[[params.footermenu.about]]
link = "about/privacy-policy"
name = "Privacy Policy"
[params.map]
enable = true
map_embed_html = "<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3580.11664371134!2d28.0304733!3d-26.1928836!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1e953db5fe719e79%3A0x9d63b2d3be70f8ba!2sUniversity%20of%20the%20Witwatersrand%2C%20Johannesburg!5e0!3m2!1sen!2sza!4v1705940529728!5m2!1sen!2sza\" width=\"600\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
URL = "http://eepurl.com/hCE_C5"
icon = "ti-comments"
text = "join our community and mailing list"
[[params.social]]
URL = "https://www.linkedin.com/company/indabax-south-africa"
icon = "ti-linkedin"
text = "connect with us on LinkedIn"
[[params.social]]
URL = "https://www.youtube.com/c/deeplearningindabax"
icon = "ti-youtube"
text = "watch our videos"
[[params.social]]
URL = "https://x.com/DeepIndabaX_ZA"
embed_url = "https://twitter.com/DeepIndabaX_ZA?ref_src=twsrc%5Etfw"
icon = "ti-twitter-alt"
text = "follow us on twitter"
[[params.social]]
URL = "https://www.instagram.com/indabax_za/"
icon = "ti-instagram"
text = "follow us on instagram"
